export const colorScheme = {
  primary: "var(--primary)",
  secondary: "var(--secondary)",
  backgroundGradient: "var(--bg-gradient)",
  background: "var(--bg)",
  backgroundSecondary: "var(--bg-secondary)",
  backgroundTertiary: "var(--bg-tertiary)",
  surface: "var(--surface)",
  selected: "var(--selected)",
  text: "var(--text)",
  textSecondary: "var(--text-secondary)",
  border: "var(--border)",
  glass: "var(--glass)",
  glassBorder: "var(--glass-border)",
  glassSelected: "var(--glass-selected)",
};
